name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dizayn3r/flutter_custom_buttons/.github/workflows/publish.yml
    # with:
    #   working-directory: path/to/package/within/repository
